export interface AdminSectionConfig {
  resource: string;
  title: string;
  description: string;
  columns: string[];
  editableFields?: string[];
  createFields?: string[];
  statusOptions?: string[];
  actions?: Array<{ key: string; label: string; tone?: 'default' | 'danger' | 'success' }>;
}

export const vpsGpuAdminSections: AdminSectionConfig[] = [
  {
    resource: 'settings',
    title: 'VPS GPU AI pricing',
    description: 'Chỉnh giá bán VPS GPU. Search key vps_gpu để lọc nhanh 3 cấu hình: tỷ giá USD, hệ số lời và phí cộng thêm mỗi giờ.',
    columns: ['id', 'setting_key', 'setting_value', 'updated_at'],
    editableFields: ['setting_value'],
    createFields: ['setting_key', 'setting_value'],
  },
      {
        resource: 'vps-gpu-offer-costs',
        title: 'VPS GPU provider costs',
        description: 'Snapshot giá vốn lấy trực tiếp từ nguồn GPU. So sánh cost USD/VNĐ, giá bán và lời dự kiến theo từng offer.',
        columns: ['id', 'offer_id', 'gpu_name', 'gpu_count', 'gpu_ram_gb', 'location', 'cost_source', 'cost_hourly_usd', 'cost_hourly_vnd', 'sale_hourly_vnd', 'profit_hourly_vnd', 'price_multiplier', 'last_seen_at'],
      },
];

export const adminPageSections: Record<string, AdminSectionConfig[]> = {
  users: [
    {
      resource: 'users',
      title: 'Người dùng',
      description: 'List/search/filter user, chỉnh số dư, rank, role, trạng thái và khóa/mở tài khoản.',
      columns: ['id', 'username', 'email', 'fullname', 'role', 'status', 'balance', 'game_balance', 'rank', 'last_ip', 'created_at'],
      editableFields: ['fullname', 'email', 'role', 'status', 'balance', 'game_balance', 'rank', 'fa_enabled', 'telegram_2fa_enabled', 'fa_type', 'lock_reason', 'locked_until', 'is_blue_tick'],
      createFields: ['username', 'email', 'password', 'fullname', 'role', 'status', 'balance', 'game_balance', 'rank'],
      statusOptions: ['active', 'locked', 'suspended', 'banned'],
      actions: [
        { key: 'bulk-delete', label: 'Khóa/Xóa đã chọn', tone: 'danger' },
      ],
    },
  ],
  deposits: [
    {
      resource: 'deposits',
      title: 'Yêu cầu nạp tiền',
      description: 'Duyệt/reject giao dịch nạp, bulk xử lý và rà pending.',
      columns: ['id', 'user_id', 'amount', 'balance_after', 'wallet_type', 'content', 'status', 'created_at'],
      editableFields: ['status', 'content', 'amount', 'wallet_type'],
      statusOptions: ['pending', 'processing', 'success', 'failed'],
      actions: [
        { key: 'approve', label: 'Duyệt', tone: 'success' },
        { key: 'reject', label: 'Từ chối', tone: 'danger' },
        { key: 'bulk-delete', label: 'Xóa đã chọn', tone: 'danger' },
        { key: 'check-new-deposits', label: 'Check pending' },
      ],
    },
    {
      resource: 'banks',
      title: 'Ngân hàng',
      description: 'Danh sách ngân hàng/QR nạp tiền đọc từ bảng legacy.',
      columns: ['id', 'name', 'account_name', 'account_number', 'is_active'],
      editableFields: ['name', 'account_name', 'account_number', 'is_active'],
      createFields: ['name', 'account_name', 'account_number', 'is_active'],
    },
    {
      resource: 'bank-logs',
      title: 'Bank API logs',
      description: 'Log đối soát ngân hàng từ PHP.',
      columns: ['id', 'status', 'message', 'created_at'],
    },
  ],
  smm: [
    {
      resource: 'smm-services',
      title: 'Services SMM',
      description: 'Quản lý service, giá tùy chỉnh, margin, trạng thái và sync provider.',
      columns: ['id', 'provider_id', 'service_id', 'name', 'category', 'rate', 'custom_price', 'min', 'max', 'status', 'total_orders'],
      editableFields: ['name', 'custom_price', 'status', 'is_deleted', 'is_auto_margin', 'margin_percent', 'name_color', 'description', 'server_info'],
      statusOptions: ['active', 'inactive'],
      actions: [
        { key: 'sync', label: 'Sync provider' },
        { key: 'bulk-delete', label: 'Ẩn/Xóa đã chọn', tone: 'danger' },
      ],
    },
    {
      resource: 'providers',
      title: 'API providers',
      description: 'Provider CRUD, exchange rate, API URL/key, health và trạng thái.',
      columns: ['id', 'name', 'type', 'service_type', 'exchange_rate', 'api_url', 'status', 'health_status', 'last_sync'],
      editableFields: ['name', 'type', 'service_type', 'is_per_unit', 'exchange_rate', 'api_key', 'api_url', 'status', 'health_status', 'balance_alert_threshold'],
      createFields: ['name', 'type', 'service_type', 'is_per_unit', 'exchange_rate', 'api_key', 'api_url', 'status', 'balance_alert_threshold'],
      statusOptions: ['active', 'inactive'],
      actions: [{ key: 'sync', label: 'Mark synced' }],
    },
    {
      resource: 'smm-orders',
      title: 'Orders SMM',
      description: 'Theo dõi order queue và cập nhật trạng thái/refund.',
      columns: ['id', 'username', 'provider_id', 'api_order_id', 'service_name', 'quantity', 'price', 'status', 'created_at'],
      editableFields: ['status', 'reason', 'is_refunded', 'refund_amount', 'start_count', 'remains'],
      statusOptions: ['Processing', 'Completed', 'Refunded', 'Canceled'],
    },
  ],
  automxh: [
    {
      resource: 'automxh-categories',
      title: 'Auto MXH categories',
      description: 'CRUD category, sort order và trạng thái.',
      columns: ['id', 'name', 'slug', 'gif', 'sort_order', 'product_count', 'status', 'created_at'],
      editableFields: ['name', 'slug', 'icon', 'gif', 'sort_order', 'status', 'is_deleted'],
      createFields: ['name', 'slug', 'icon', 'gif', 'sort_order', 'status'],
      statusOptions: ['active', 'inactive'],
    },
    {
      resource: 'automxh-products',
      title: 'Auto MXH products',
      description: 'Thêm/sửa dịch vụ con/tab hiển thị trong từng mục cha Facebook, Instagram...',
      columns: ['id', 'category_id', 'name', 'badge', 'description', 'api_provider_id', 'api_service_id', 'price', 'cost', 'variant_count', 'status', 'created_at'],
      editableFields: ['category_id', 'api_provider_id', 'api_service_id', 'name', 'slug', 'badge', 'price', 'cost', 'type', 'description', 'input_label', 'input_placeholder', 'buyer_label', 'buyer_placeholder', 'custom_inputs', 'status', 'is_deleted'],
      createFields: ['category_id', 'api_provider_id', 'api_service_id', 'name', 'slug', 'badge', 'price', 'cost', 'type', 'description', 'input_label', 'input_placeholder', 'buyer_label', 'buyer_placeholder', 'custom_inputs', 'status'],
      statusOptions: ['active', 'inactive'],
    },
    {
      resource: 'automxh-orders',
      title: 'Auto MXH orders',
      description: 'Quản lý order, trạng thái, số lượng và perfection/basic status.',
      columns: ['id', 'user_id', 'product_id', 'variant_id', 'api_provider_id', 'api_order_id', 'price', 'status', 'created_at'],
      editableFields: ['status', 'price', 'cost_price', 'buyer_info', 'api_order_id', 'api_response', 'api_status_log', 'perfection_content', 'perfection_image', 'avatar_path', 'additional_files', 'confirm_1', 'confirm_2', 'is_exported'],
      statusOptions: ['pending', 'processing', 'completed', 'canceled'],
    },
    {
      resource: 'automxh-variants',
      title: 'Auto MXH variants',
      description: 'Máy chủ/gói con nằm dưới từng dịch vụ cha, note vàng bên trang đặt hàng, giá vốn và API service id.',
      columns: ['id', 'product_id', 'name', 'description', 'api_provider_id', 'api_service_id', 'quantity', 'price', 'cost', 'status', 'allow_avatar', 'allow_files'],
      editableFields: ['product_id', 'api_provider_id', 'api_service_id', 'quantity', 'name', 'price', 'cost', 'original_price', 'description', 'badge', 'type', 'status', 'allow_avatar', 'allow_files', 'is_deleted'],
      createFields: ['product_id', 'api_provider_id', 'api_service_id', 'quantity', 'name', 'price', 'cost', 'original_price', 'description', 'badge', 'type', 'status', 'allow_avatar', 'allow_files'],
      statusOptions: ['active', 'inactive'],
    },
  ],
  'meta-support': [
    {
      resource: 'meta-support-orders',
      title: 'Auto kích nút Meta orders',
      description: 'Quản lý đơn Auto kích nút + Chat Support Meta. Admin cập nhật trạng thái và ghi chú trả về cho user.',
      columns: ['id', 'user_id', 'contact', 'gmail', 'quantity', 'price', 'status', 'admin_note', 'updated_at', 'created_at'],
      editableFields: ['contact', 'gmail', 'quantity', 'price', 'note', 'admin_note', 'status'],
      statusOptions: ['pending', 'processing', 'completed', 'canceled'],
    },
  ],
  'support-tiktok': [
    {
      resource: 'tiktok-orders',
      title: 'Support TikTok orders',
      description: 'Quản lý toàn bộ order support TikTok: trạng thái, hạn dùng, gia hạn, liên hệ và người mua.',
      columns: ['id', 'user_id', 'region', 'service_key', 'service_name', 'tiktok_id', 'buyer_name', 'price', 'status', 'ngay_het_han', 'updated_at'],
      editableFields: ['region', 'service_key', 'service_name', 'tiktok_id', 'buyer_name', 'buyer_contact', 'price', 'status', 'ngay_gia_han', 'ngay_het_han'],
      createFields: ['user_id', 'region', 'service_key', 'service_name', 'tiktok_id', 'buyer_name', 'buyer_contact', 'price', 'status', 'ngay_gia_han', 'ngay_het_han'],
      statusOptions: ['pending', 'active', 'processing', 'completed', 'canceled', 'expired'],
    },
    {
      resource: 'tiktok-service-menus',
      title: 'Menu dịch vụ',
      description: 'CRUD menu/region hiển thị trong module support TikTok.',
      columns: ['id', 'name', 'slug', 'display_order', 'status', 'created_at'],
      editableFields: ['name', 'slug', 'display_order', 'status'],
      createFields: ['name', 'slug', 'display_order', 'status'],
      statusOptions: ['active', 'inactive'],
    },
    {
      resource: 'tiktok-region-services',
      title: 'Region services',
      description: 'CRUD dịch vụ theo khu vực: service_key, giá, mô tả, thứ tự và trạng thái.',
      columns: ['id', 'region_slug', 'name', 'service_key', 'price', 'display_order', 'status', 'updated_at'],
      editableFields: ['region_slug', 'name', 'service_key', 'price', 'description', 'display_order', 'status'],
      createFields: ['region_slug', 'name', 'service_key', 'price', 'description', 'display_order', 'status'],
      statusOptions: ['active', 'inactive'],
    },
    {
      resource: 'admin-private-messages',
      title: 'Tin nhắn admin',
      description: 'Gửi private message từ admin tới user, giới hạn số lần hiển thị và trạng thái.',
      columns: ['id', 'admin_id', 'user_id', 'message', 'show_limit', 'shown_count', 'status', 'created_at'],
      editableFields: ['message', 'show_limit', 'shown_count', 'status'],
      createFields: ['admin_id', 'user_id', 'message', 'show_limit', 'shown_count', 'status'],
      statusOptions: ['active', 'inactive'],
    },
    {
      resource: 'message-reports',
      title: 'Message reports',
      description: 'Báo cáo tin nhắn và trạng thái xử lý.',
      columns: ['id', 'message_id', 'reporter_id', 'reason', 'status', 'created_at'],
      editableFields: ['status'],
      statusOptions: ['pending', 'reviewed', 'dismissed'],
    },
  ],
  resources: [
    {
      resource: 'resources',
      title: 'MMO resources',
      description: 'CRUD tài nguyên, giá, stock, trạng thái, API tài khoản game/MMO và margin.',
      columns: ['id', 'product_code', 'category', 'category_id', 'title', 'price', 'stock', 'sold_count', 'status', 'is_pinned', 'api_provider_id'],
      editableFields: ['product_code', 'title', 'description', 'category', 'category_id', 'price', 'original_price', 'thumbnail', 'resource_type', 'stock', 'sold_count', 'download_url', 'content', 'product_content', 'product_note', 'tags', 'status', 'featured', 'is_pinned', 'api_provider_id', 'api_product_id', 'is_auto', 'is_auto_margin', 'margin_percent', 'custom_badge', 'display_order', 'is_deleted'],
      createFields: ['product_code', 'title', 'description', 'category', 'category_id', 'price', 'original_price', 'thumbnail', 'resource_type', 'stock', 'download_url', 'content', 'product_content', 'product_note', 'tags', 'status', 'featured', 'is_pinned', 'created_by', 'api_provider_id', 'api_product_id', 'is_auto', 'is_auto_margin', 'margin_percent', 'custom_badge', 'display_order'],
      statusOptions: ['active', 'inactive', 'out_of_stock'],
      actions: [{ key: 'sync', label: 'Sync MMO/API game' }],
    },
    {
      resource: 'resource-categories',
      title: 'Resource categories',
      description: 'Danh mục tài nguyên MMO, mapping API category và thứ tự hiển thị.',
      columns: ['id', 'parent_id', 'name', 'slug', 'display_order', 'status', 'api_provider_id', 'api_category_id'],
      editableFields: ['parent_id', 'name', 'slug', 'icon', 'image', 'description', 'display_order', 'status', 'is_deleted', 'api_provider_id', 'api_category_id'],
      createFields: ['parent_id', 'name', 'slug', 'icon', 'image', 'description', 'display_order', 'status', 'api_provider_id', 'api_category_id'],
      statusOptions: ['active', 'inactive'],
    },
    {
      resource: 'resource-orders',
      title: 'Resource sales',
      description: 'Đơn mua tài nguyên và trạng thái giao hàng.',
      columns: ['id', 'user_id', 'resource_id', 'quantity', 'total_price', 'status', 'payment_method', 'is_exported', 'created_at'],
      editableFields: ['status', 'total_price', 'quantity', 'payment_method', 'download_count', 'max_downloads', 'expires_at', 'delivery_data', 'is_exported', 'exported_at'],
      statusOptions: ['pending', 'completed', 'cancelled', 'refunded'],
    },
    {
      resource: 'providers',
      title: 'MMO API providers',
      description: 'Provider API tài khoản game/MMO dùng chung bảng api_providers.',
      columns: ['id', 'name', 'type', 'service_type', 'exchange_rate', 'api_url', 'status', 'health_status'],
      editableFields: ['name', 'type', 'service_type', 'exchange_rate', 'api_key', 'api_url', 'status', 'health_status'],
      createFields: ['name', 'type', 'service_type', 'exchange_rate', 'api_key', 'api_url', 'status'],
      statusOptions: ['active', 'inactive'],
    },
  ],
  forum: [
    {
      resource: 'forum-categories',
      title: 'Forum categories',
      description: 'CRUD danh mục forum.',
      columns: ['id', 'name', 'description', 'priority', 'created_at'],
      editableFields: ['name', 'description', 'priority'],
      createFields: ['name', 'description', 'priority'],
    },
    {
      resource: 'forum-forums',
      title: 'Forum folders',
      description: 'Folder/forum con, role được đăng và priority.',
      columns: ['id', 'category_id', 'parent_id', 'name', 'slug', 'priority', 'allowed_posting_roles'],
      editableFields: ['category_id', 'parent_id', 'name', 'slug', 'description', 'icon', 'priority', 'allowed_posting_roles', 'last_post_id'],
      createFields: ['category_id', 'parent_id', 'name', 'slug', 'description', 'icon', 'priority', 'allowed_posting_roles'],
    },
    {
      resource: 'forum-threads',
      title: 'Threads',
      description: 'Duyệt/ẩn/ghim/khóa thread forum. Bài ghim luôn được đẩy lên đầu trang Forum MMO.',
      columns: ['id', 'forum_id', 'user_id', 'title', 'views', 'is_pinned', 'is_locked', 'status', 'is_deleted', 'updated_at', 'created_at'],
      editableFields: ['forum_id', 'user_id', 'title', 'slug', 'status', 'is_pinned', 'is_locked', 'is_deleted'],
      createFields: ['forum_id', 'user_id', 'title', 'slug', 'status', 'is_pinned', 'is_locked'],
      statusOptions: ['active', 'hidden', 'deleted', 'pending', 'rejected'],
      actions: [
        { key: 'approve', label: 'Duyệt', tone: 'success' },
        { key: 'reject', label: 'Từ chối', tone: 'danger' },
        { key: 'pin', label: 'Ghim', tone: 'success' },
        { key: 'unpin', label: 'Bỏ ghim' },
        { key: 'bulk-approve', label: 'Duyệt hàng loạt', tone: 'success' },
        { key: 'bulk-reject', label: 'Từ chối hàng loạt', tone: 'danger' },
      ],
    },
    {
      resource: 'forum-posts',
      title: 'Posts',
      description: 'Duyệt bài trả lời, hidden/restore/delete.',
      columns: ['id', 'thread_id', 'user_id', 'is_first_post', 'content', 'status', 'is_deleted', 'updated_at', 'created_at'],
      editableFields: ['content', 'status', 'is_deleted'],
      statusOptions: ['active', 'pending', 'rejected', 'hidden', 'deleted'],
      actions: [
        { key: 'approve', label: 'Duyệt', tone: 'success' },
        { key: 'reject', label: 'Từ chối', tone: 'danger' },
        { key: 'bulk-approve', label: 'Duyệt hàng loạt', tone: 'success' },
        { key: 'bulk-reject', label: 'Từ chối hàng loạt', tone: 'danger' },
      ],
    },
    {
      resource: 'forum-ads',
      title: 'Forum ads',
      description: 'Duyệt quảng cáo forum, thời hạn chạy và lý do reject.',
      columns: ['id', 'user_id', 'status', 'price_vnd', 'duration_days', 'link_url', 'active_from', 'active_to'],
      editableFields: ['status', 'price_vnd', 'duration_days', 'image_path', 'link_url', 'reject_reason', 'uploaded_at', 'approved_at', 'active_from', 'active_to', 'admin_id'],
      createFields: ['user_id', 'status', 'price_vnd', 'duration_days', 'image_path', 'link_url', 'reject_reason', 'active_from', 'active_to', 'admin_id'],
      statusOptions: ['awaiting_upload', 'pending', 'approved', 'rejected', 'expired'],
    },
    {
      resource: 'forum-reports',
      title: 'Forum reports',
      description: 'Báo cáo bài viết/thành viên và trạng thái xử lý.',
      columns: ['id', 'post_id', 'user_id', 'reported_user_id', 'reason', 'status', 'created_at'],
      editableFields: ['status', 'details'],
      statusOptions: ['pending', 'reviewed', 'resolved', 'dismissed', 'processed', 'ignored'],
    },
    {
      resource: 'forum-badges',
      title: 'Forum badges',
      description: 'Badge thành viên và tiêu chí trao badge.',
      columns: ['id', 'name', 'icon', 'color', 'criteria_type', 'criteria_value'],
      editableFields: ['name', 'icon', 'color', 'description', 'criteria_type', 'criteria_value'],
      createFields: ['name', 'icon', 'color', 'description', 'criteria_type', 'criteria_value'],
    },
    {
      resource: 'forum-prefixes',
      title: 'Forum prefixes',
      description: 'Prefix thread theo màu và priority.',
      columns: ['id', 'name', 'color', 'priority'],
      editableFields: ['name', 'color', 'priority'],
      createFields: ['name', 'color', 'priority'],
    },
  ],
  card: [
    {
      resource: 'card-rates',
      title: 'Card rates',
      description: 'Tỉ lệ đổi/mua/topup thẻ theo telco và mệnh giá.',
      columns: ['id', 'telco', 'value', 'rate_exchange', 'rate_buy', 'type', 'is_active'],
      editableFields: ['telco', 'value', 'rate_exchange', 'rate_buy', 'type', 'is_active'],
      createFields: ['telco', 'value', 'rate_exchange', 'rate_buy', 'type', 'is_active'],
      statusOptions: ['1', '0'],
    },
    {
      resource: 'card-orders',
      title: 'Card orders',
      description: 'History, refund, API order id và trạng thái đơn thẻ.',
      columns: ['id', 'user_id', 'type', 'telco', 'card_amount', 'amount', 'serial', 'api_order_id', 'status', 'created_at'],
      editableFields: ['status', 'note', 'amount', 'api_order_id'],
      statusOptions: ['pending', 'success', 'failed', 'refunded'],
      actions: [{ key: 'refund', label: 'Refund', tone: 'success' }],
    },
  ],
  'game-market': [
    {
      resource: 'game-items',
      title: 'Game market items',
      description: 'Bài đăng mua bán game theo danh mục, cần admin duyệt trước khi xuất hiện ngoài user page.',
      columns: ['id', 'code', 'seller_id', 'title', 'category', 'price', 'stock', 'status', 'is_pinned'],
      editableFields: ['code', 'seller_id', 'title', 'category', 'tag', 'badge', 'badge_color', 'price', 'stock', 'prep_time', 'accounts_stock', 'original_price', 'thumbnail', 'description', 'images', 'features', 'rank', 'skins', 'champs', 'account_details', 'status', 'delivery_method', 'is_pinned', 'pinned_until'],
      createFields: ['id', 'code', 'seller_id', 'title', 'category', 'tag', 'badge', 'badge_color', 'price', 'stock', 'prep_time', 'accounts_stock', 'original_price', 'thumbnail', 'description', 'images', 'features', 'rank', 'skins', 'champs', 'account_details', 'status', 'delivery_method', 'is_pinned', 'pinned_until'],
      statusOptions: ['pending', 'selling', 'sold', 'hidden', 'rejected'],
      actions: [
        { key: 'approve', label: 'Duyệt', tone: 'success' },
        { key: 'reject', label: 'Từ chối', tone: 'danger' },
        { key: 'pin', label: 'Ghim', tone: 'success' },
        { key: 'unpin', label: 'Bỏ ghim' },
        { key: 'bulk-approve', label: 'Duyệt hàng loạt', tone: 'success' },
        { key: 'bulk-reject', label: 'Từ chối hàng loạt', tone: 'danger' },
      ],
    },
    {
      resource: 'game-orders',
      title: 'Game market orders',
      description: 'Listing/order game market theo DB hiện có.',
      columns: ['id', 'buyer_id', 'seller_id', 'item_id', 'amount', 'status', 'rating', 'created_at'],
      editableFields: ['buyer_id', 'seller_id', 'item_id', 'stock_id', 'amount', 'delivered_data', 'status', 'rating', 'review'],
      createFields: ['id', 'buyer_id', 'seller_id', 'item_id', 'stock_id', 'amount', 'delivered_data', 'status'],
      statusOptions: ['completed', 'failed', 'refunded', 'processing'],
    },
  ],
  'find-job': [
    {
      resource: 'find-jobs',
      title: 'Find Job posts',
      description: 'Quản lý tin tuyển dụng, duyệt trạng thái và ghim tin tốt lên đầu trang Find Job MMO.',
      columns: ['id', 'title', 'category', 'user_id', 'posted_by', 'budget_min', 'price_min', 'budget_max', 'price_max', 'status', 'approval_status', 'is_pinned', 'updated_at', 'created_at', 'posted_at'],
      editableFields: ['title', 'description', 'category', 'budget_min', 'price_min', 'budget_max', 'price_max', 'status', 'approval_status', 'is_pinned'],
      statusOptions: ['pending', 'approved', 'rejected', 'open', 'filled', 'closed'],
      actions: [
        { key: 'approve', label: 'Duyệt', tone: 'success' },
        { key: 'reject', label: 'Từ chối', tone: 'danger' },
        { key: 'pin', label: 'Ghim', tone: 'success' },
        { key: 'unpin', label: 'Bỏ ghim' },
        { key: 'bulk-approve', label: 'Duyệt hàng loạt', tone: 'success' },
        { key: 'bulk-reject', label: 'Từ chối hàng loạt', tone: 'danger' },
      ],
    },
  ],
  accounting: [
    {
      resource: 'transactions',
      title: 'Accounting transactions',
      description: 'Tổng hợp giao dịch toàn hệ thống để hậu kiểm/kế toán.',
      columns: ['id', 'user_id', 'type', 'amount', 'balance_after', 'status', 'content', 'created_at'],
      editableFields: ['status', 'content'],
      statusOptions: ['pending', 'success', 'failed'],
    },
    {
      resource: 'resource-orders',
      title: 'Resource sales',
      description: 'Doanh số tài nguyên.',
      columns: ['id', 'user_id', 'resource_id', 'quantity', 'total_price', 'status', 'created_at'],
      editableFields: ['status', 'total_price', 'quantity', 'payment_method', 'delivery_data'],
      statusOptions: ['pending', 'completed', 'cancelled', 'refunded'],
    },
    {
      resource: 'card-orders',
      title: 'Card history',
      description: 'Luồng thẻ cào phục vụ đối soát.',
      columns: ['id', 'user_id', 'type', 'telco', 'amount', 'status', 'created_at'],
      editableFields: ['status', 'note'],
      statusOptions: ['pending', 'success', 'failed', 'refunded'],
    },
    {
      resource: 'admin-audit-logs',
      title: 'Admin audit logs',
      description: 'Log hành động admin legacy.',
      columns: ['id', 'admin_id', 'target_user_id', 'action', 'description', 'ip_address', 'created_at'],
    },
  ],
  settings: [
    {
      resource: 'settings',
      title: 'Settings',
      description: 'Cài đặt chung, giao diện, API domain/key, Telegram/Discord config dạng key-value.',
      columns: ['id', 'setting_key', 'setting_value', 'updated_at'],
      editableFields: ['setting_value'],
      createFields: ['setting_key', 'setting_value'],
    },
    {
      resource: 'banks',
      title: 'Bank accounts',
      description: 'Bank CRUD cho luồng nạp tiền.',
      columns: ['id', 'name', 'account_name', 'account_number', 'is_active'],
      editableFields: ['name', 'account_name', 'account_number', 'is_active'],
      createFields: ['name', 'account_name', 'account_number', 'is_active'],
    },
    {
      resource: 'providers',
      title: 'Providers',
      description: 'API provider chung.',
      columns: ['id', 'name', 'service_type', 'api_url', 'status', 'health_status'],
      editableFields: ['name', 'service_type', 'api_key', 'api_url', 'status', 'health_status'],
      createFields: ['name', 'service_type', 'api_key', 'api_url', 'status'],
      statusOptions: ['active', 'inactive'],
    },
  ],
  security: [
    {
      resource: 'registration-ips',
      title: 'IP đăng ký',
      description: 'Theo dõi số tài khoản tạo từ cùng IP. IP có từ 10 tài khoản trở lên được đánh dấu rủi ro, admin có thể ban/mở ban và khóa/mở user theo IP.',
      columns: ['id', 'ip', 'accounts_count', 'active_count', 'locked_count', 'banned_state', 'blacklisted_state', 'last_seen', 'sample_users'],
      statusOptions: ['limit-risk', 'banned', 'blacklisted', 'clear'],
      actions: [
        { key: 'block-ip', label: 'Ban IP', tone: 'danger' },
        { key: 'unblock-ip', label: 'Mở IP', tone: 'success' },
        { key: 'lock-users-by-ip', label: 'Khóa users', tone: 'danger' },
        { key: 'unlock-users-by-ip', label: 'Mở users', tone: 'success' },
        { key: 'bulk-block-ip', label: 'Ban IP đã chọn', tone: 'danger' },
        { key: 'bulk-unblock-ip', label: 'Mở IP đã chọn', tone: 'success' },
      ],
    },
    {
      resource: 'ip-blacklist',
      title: 'IP blacklist',
      description: 'Chặn/mở IP.',
      columns: ['id', 'ip_address', 'reason', 'created_at'],
      editableFields: ['ip_address', 'reason'],
      createFields: ['ip_address', 'reason'],
    },
    {
      resource: 'banned-ips',
      title: 'Banned IPs',
      description: 'IP ban có thời hạn.',
      columns: ['id', 'ip', 'reason', 'banned_by', 'user_id', 'expire_at', 'created_at'],
      editableFields: ['ip', 'reason', 'banned_by', 'user_id', 'expire_at'],
      createFields: ['ip', 'reason', 'banned_by', 'user_id', 'expire_at'],
    },
    {
      resource: 'activity-logs',
      title: 'Activity logs',
      description: 'Audit trail và điều tra hoạt động.',
      columns: ['id', 'user_id', 'activity', 'ip_address', 'created_at'],
    },
    {
      resource: 'security-logs',
      title: 'Security logs',
      description: 'Log bảo mật, auto-ban và hành vi bất thường từ hệ thống legacy/Next.',
      columns: ['id', 'event_type', 'severity', 'ip', 'uri', 'payload', 'auto_banned', 'created_at'],
    },
  ],
  'ip-blocks': [
    {
      resource: 'registration-ips',
      title: 'IP đăng ký',
      description: 'Một IP chỉ được tạo tối đa 10 tài khoản. Vượt ngưỡng sẽ tự động ban và hiện popup liên hệ admin.',
      columns: ['id', 'ip', 'accounts_count', 'active_count', 'locked_count', 'banned_state', 'blacklisted_state', 'last_seen', 'sample_users'],
      statusOptions: ['limit-risk', 'banned', 'blacklisted', 'clear'],
      actions: [
        { key: 'block-ip', label: 'Ban IP', tone: 'danger' },
        { key: 'unblock-ip', label: 'Mở IP', tone: 'success' },
        { key: 'lock-users-by-ip', label: 'Khóa users', tone: 'danger' },
        { key: 'unlock-users-by-ip', label: 'Mở users', tone: 'success' },
        { key: 'bulk-block-ip', label: 'Ban IP đã chọn', tone: 'danger' },
        { key: 'bulk-unblock-ip', label: 'Mở IP đã chọn', tone: 'success' },
      ],
    },
    {
      resource: 'banned-ips',
      title: 'Banned IPs',
      description: 'Danh sách IP đang bị ban, bao gồm auto-ban do tạo quá nhiều account.',
      columns: ['id', 'ip', 'reason', 'banned_by', 'user_id', 'expire_at', 'created_at'],
      editableFields: ['ip', 'reason', 'banned_by', 'user_id', 'expire_at'],
      createFields: ['ip', 'reason', 'banned_by', 'user_id', 'expire_at'],
    },
    {
      resource: 'ip-blacklist',
      title: 'IP blacklist',
      description: 'Blacklist truy cập kiểu legacy.',
      columns: ['id', 'ip_address', 'reason', 'created_at'],
      editableFields: ['ip_address', 'reason'],
      createFields: ['ip_address', 'reason'],
    },
    {
      resource: 'security-logs',
      title: 'Security logs',
      description: 'Lịch sử auto-ban/anti-cheat.',
      columns: ['id', 'event_type', 'severity', 'ip', 'uri', 'payload', 'auto_banned', 'created_at'],
    },
  ],
  'activity-logs': [
    {
      resource: 'activity-logs',
      title: 'Activity logs',
      description: 'Toàn bộ log hoạt động user/admin.',
      columns: ['id', 'user_id', 'activity', 'ip_address', 'user_agent', 'created_at'],
    },
    {
      resource: 'bank-logs',
      title: 'Bank API logs',
      description: 'Log bank API từ source cũ.',
      columns: ['id', 'status', 'message', 'created_at'],
    },
  ],
  orders: [
    {
      resource: 'smm-orders',
      title: 'SMM orders',
      description: 'Đơn SMM.',
      columns: ['id', 'username', 'api_order_id', 'service_name', 'quantity', 'price', 'status', 'created_at'],
      editableFields: ['status', 'reason', 'is_refunded', 'refund_amount'],
      statusOptions: ['Processing', 'Completed', 'Refunded', 'Canceled'],
    },
    {
      resource: 'automxh-orders',
      title: 'Auto MXH orders',
      description: 'Đơn Auto MXH.',
      columns: ['id', 'user_id', 'title', 'quantity', 'amount', 'status', 'created_at'],
      editableFields: ['status', 'amount', 'quantity', 'buyer_info'],
      statusOptions: ['pending', 'processing', 'completed', 'failed', 'refunded'],
    },
    {
      resource: 'card-orders',
      title: 'Card orders',
      description: 'Đơn thẻ.',
      columns: ['id', 'user_id', 'type', 'telco', 'amount', 'status', 'created_at'],
      editableFields: ['status', 'note'],
      statusOptions: ['pending', 'success', 'failed', 'refunded'],
    },
  ],
};
