CREATE TABLE IF NOT EXISTS proxy_orders (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  kind VARCHAR(20) NOT NULL DEFAULT 'buy',
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  package_id VARCHAR(64) NULL,
  package_name VARCHAR(255) NULL,
  location VARCHAR(64) NULL,
  proxy_type VARCHAR(64) NULL,
  protocol VARCHAR(20) NULL,
  days INT NOT NULL DEFAULT 0,
  quantity INT NOT NULL DEFAULT 0,
  unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
  total_price DECIMAL(15,2) NOT NULL DEFAULT 0,
  provider_order_ref VARCHAR(100) NULL,
  provider_payload LONGTEXT NULL,
  target_proxy_ids TEXT NULL,
  note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_proxy_orders_user_status (user_id, status),
  KEY idx_proxy_orders_kind_created (kind, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proxy_items (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  order_id INT NULL,
  provider_proxy_id VARCHAR(100) NOT NULL,
  package_id VARCHAR(64) NULL,
  package_name VARCHAR(255) NULL,
  location VARCHAR(64) NULL,
  proxy_type VARCHAR(64) NULL,
  protocol VARCHAR(20) NULL,
  ip_address VARCHAR(120) NULL,
  port INT NULL,
  username VARCHAR(255) NULL,
  password VARCHAR(255) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  expired_at DATETIME NULL,
  provider_created_at DATETIME NULL,
  last_synced_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_provider_proxy_id (provider_proxy_id),
  KEY idx_proxy_items_user_status (user_id, status),
  KEY idx_proxy_items_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
