import { StorefrontData } from "./types";

export const storefrontFallback: StorefrontData = {
  settings: {
    brand_name: "TRUNGTAMMMO.VN",
    hero_title: "VPS tốc độ cao cho MMO, website, automation bot và hơn thế nữa",
    hero_subtitle:
      "Chọn gói VPS phù hợp, thanh toán bằng số dư và quản lý máy chủ tập trung trong một giao diện gọn, nhanh và hiện đại.",
    hero_badge: "Hệ thống VPS tự động",
    support_link: "https://zalo.me/3482369546728805278",
    announcement:
      "Danh mục VPS, giá bán và trạng thái mở bán sẽ được đồng bộ để bạn lựa chọn nhanh hơn và mua ngay trực tiếp trên hệ thống.",
    theme_default: "dark",
    intro_customer_count: "16890",
    addon_cpu_price: 15000,
    addon_ram_price: 15000,
    addon_disk_price: 5000,
    addon_disk_step: 10,
  },
  stats: {
    total_orders: 128,
    live_instances: 314,
    total_customers: 89,
  },
  operatingSystems: [
    "Ubuntu 24.04 LTS",
    "Ubuntu 22.04 LTS",
    "Debian 12",
    "Debian 11",
    "AlmaLinux 9",
    "Rocky Linux 9",
    "CentOS Stream 9",
    "Windows Server 2022",
    "Windows Server 2019",
    "Windows 11 Pro",
  ],
  items: [
    {
      id: 1,
      sku: "VPS-START-01",
      title: "VPS Start Node",
      slug: "vps-start-node",
      short_description: "Gói khởi động gọn nhẹ, độ trễ tốt cho web và bot.",
      description:
        "Phù hợp cho web app nhỏ, bot MMO, API gateway và các workflow cần khởi tạo nhanh.",
      sale_price: 149000,
      compare_price: 189000,
      billing_cycle_code: "monthly",
      billing_cycle_label: "1 thang",
      addon_cpu: 0,
      addon_ram: 0,
      addon_disk: 0,
      badge_text: "Bán chạy",
      hero_gradient_from: "#0f766e",
      hero_gradient_to: "#1d4ed8",
      is_featured: 1,
      cpu_label: "2 vCPU",
      ram_label: "4 GB RAM",
      disk_label: "60 GB NVMe",
      bandwidth_label: "Băng thông cơ bản không giới hạn",
      operating_system_name: "Ubuntu 22.04 LTS",
    },
    {
      id: 2,
      sku: "VPS-GROW-02",
      title: "VPS Growth Rack",
      slug: "vps-growth-rack",
      short_description: "Cân bằng giữa giá, sức mạnh và khả năng mở rộng.",
      description:
        "Hợp với hệ thống chạy ads tools, crawler, backend node và các stack cần RAM khá.",
      sale_price: 289000,
      compare_price: 339000,
      billing_cycle_code: "monthly",
      billing_cycle_label: "1 thang",
      addon_cpu: 2,
      addon_ram: 2,
      addon_disk: 20,
      badge_text: "Mở rộng nhanh",
      hero_gradient_from: "#0f172a",
      hero_gradient_to: "#f97316",
      is_featured: 1,
      cpu_label: "4 vCPU",
      ram_label: "8 GB RAM",
      disk_label: "120 GB NVMe",
      bandwidth_label: "Có snapshot sao lưu",
      operating_system_name: "Debian 12",
    },
    {
      id: 3,
      sku: "VPS-PRO-03",
      title: "VPS Pro Cluster",
      slug: "vps-pro-cluster",
      short_description: "Dành cho seller lớn, tác vụ nặng và worker song song.",
      description:
        "Tối ưu cho workload lớn hơn, phù hợp backend API, multi-bot và dashboard cần nhiều tài nguyên.",
      sale_price: 499000,
      compare_price: 579000,
      billing_cycle_code: "monthly",
      billing_cycle_label: "1 thang",
      addon_cpu: 4,
      addon_ram: 4,
      addon_disk: 40,
      badge_text: "Tải cao",
      hero_gradient_from: "#1e293b",
      hero_gradient_to: "#14b8a6",
      is_featured: 0,
      cpu_label: "8 vCPU",
      ram_label: "16 GB RAM",
      disk_label: "240 GB NVMe",
      bandwidth_label: "Sẵn sàng tự gia hạn",
      operating_system_name: "AlmaLinux 9",
    },
  ],
};
